export const FETCH_CUR_API_DATA='FETCH_DATA';

export const FETCH_CUR_API_REQUEST='FETCH_CUR_API_REQUEST';

export const FETCH_CUR_API_SUCCESS='FETCH_CUR_API_SUCCESS';

export const FETCH_CUR_API_FAILURE='FETCH_CUR_API_FAILURE';

